version: "3.8"

services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
