version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb+srv://warehouse:zUH0T0ygcCxlLfnO@projects.eg1tndb.mongodb.net/Collabwrite?authSource=admin
      - PORT=3001
      - JWT_SECRET=n3AGBjPX7Zyl
      - REDIS_URL_LOCAL=redis://redis:6379
      - REDIS_URL=redis://default:K6F6fcSfkQbVcS8tPPycPuqkyKUVh2Ah@redis-17992.c330.asia-south1-1.gce.redns.redis-cloud.com:17992
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=https://ph-dev-task.onrender.com/api/v1
      - LOCAL_API_URL=http://localhost:3001/api/v1
      - NEXT_PUBLIC_API_URL=https://ph-dev-task.onrender.com/api/v1
      - NEXT_PUBLIC_LOCAL_API_URL=http://localhost:3001/api/v1
      - JWT_SECRET=n3AGBjPX7Zyl
      - JWT_EXPIRES_HOUR=12
      - NEXT_PUBLIC_SOCKET_URL_LOCAL=http://localhost:3001
      - NEXT_PUBLIC_SOCKET_URL=https://ph-dev-task.onrender.com
    depends_on:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
